services:
  # ----- OPERATOR (CLIENT) MACHINE -----
  operator:
    build:
      context: .
      dockerfile: Dockerfile
    image: ender  # Explicitly tag the built image
    container_name: operator
    hostname: operator
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "4444:4444"
      - "8080:8080"
      - "55552:55552"
      - "55553:55553"
    environment:
      - RPCPASS=memes
      - RPCPORT=1337
    volumes:
      - ./src/config_files/msfconsole.rc:/usr/src/metasploit-framework/docker/msfconsole.rc:ro
    networks:
      localnet:
        ipv4_address: 10.1.1.2


  # ----- VICTIM MACHINES -----
  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    hostname: metasploitable2
    entrypoint: bash -c '/bin/services.sh && tail -f /dev/null'
    command: sleep infinite
    networks:
      localnet:
        ipv4_address: 10.1.1.3

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1